version: 0.0

os: linux

files:

permissions:

hooks:
  BeforeInstall:
    - location: scripts/code_deploy/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/code_deploy/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/code_deploy/application_start.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/code_deploy/application_stop.sh
      timeout: 300
      runas: root
