version: 0.0

os: linux

env:
  # secrets-manager:
  #   DOCKERHUB_PASS: "/dockerhub/credentials:password" -- using aws secret manager
  #   DOCKERHUB_USERNAME: "/dockerhub/credentials:username" -- using aws secret manager
  variables:
    DOCKERHUB_USERNAME: "dipuvish5"
    IMAGE_REPO_NAME: "nest_api_server"
    IMAGE_TAG:  "latest"
    DOCKERHUB_PASS: "deepakv123"

# Files section is not required because we are directly using docker and container and container has all the required files already
# files: 

permissions:

hooks:
  BeforeInstall:
    - location: scripts/code_deploy/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/code_deploy/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/code_deploy/application_start.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/code_deploy/application_stop.sh
      timeout: 300
      runas: root
